repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        files: \.py$
      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        files: \.py$
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        files: \.py$
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        files: \.py$
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        files: \.py$
      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        files: \.py$